version: "3.8"
services:
  assignment:
    restart: on-failure
    build: ./
    expose:
      - "8090"
    ports:
      - 8090:8090
  sonarqube:
    image: sonarqube:latest
    ports:
      - 9000:9000